# Generated by Django 5.0 on 2023-12-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(default=12345, max_length=200),
            preserve_default=False,
        ),
    ]
